version: '3.4'

services:
  MultiCacheDemoNet50:
    image: multi-cache-demo-net50
    container_name: multi-cache-demo-net50
    links:
      - MultiCacheDemoNet50Redis
    build:
      context: .
    ports:
      - "0.0.0.0:5000:80"
    networks:
      - multi-cache-demo-net50-network
    environment:
      - API_URL=Api:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings__Host=multi-cache-demo-net50-redis:6379

  MultiCacheDemoNet50Redis:
    image: redis
    container_name: multi-cache-demo-net50-redis
    expose:
      - 6379
    networks:
      - multi-cache-demo-net50-network

networks:
  multi-cache-demo-net50-network: