name: Nuget Package for nuget.org

on:
  release:
    types: [published]
jobs:
  multicache-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build --configuration Release ./src/MultiCache/MultiCache.csproj
    - name: Package
      run: dotnet pack --configuration Release ./src/MultiCache/MultiCache.csproj
    - name: Upload
      run: dotnet nuget push ./src/MultiCache/bin/Release/*.nupkg --api-key ${{ secrets.NugetApiKey }} --source https://api.nuget.org/v3/index.json
